; ====================================================================================
; Dead by Daylight - Profil Compétitif (par Jules)
; PROFIL C : Haute Config
; OBJECTIF : Stabilité, FPS élevés, options graphiques améliorées.
; ====================================================================================

[/Script/Engine.GameUserSettings]
; --- Options d'Affichage et de Synchronisation ---
bUseVSync=False
FullscreenMode=1
PreferredFullscreenMode=1
bUseDynamicResolution=False
FrameRateLimit=0.000000

; --- Résolution (Gérée par le script) ---
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080

; --- Options Diverses ---
bUseDesiredScreenHeight=False
bUseHDRDisplayOutput=False
AudioQualityLevel=1

[ScalabilityGroups]
; Qualité des textures et distance d'affichage augmentées pour ce profil.
sg.ResolutionQuality=100.000000
sg.ViewDistanceQuality=2              ; QUALITÉ DISTANCE POUR PROFIL C. 2 = Haute.
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=2                   ; QUALITÉ DES TEXTURES POUR PROFIL C. 2 = Haute.
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.AnimationQuality=0
