; ====================================================================================
; Dead by Daylight - Profil Compétitif (par Jules)
; PROFIL D : Très Haute Config
; OBJECTIF : Stabilité, FPS élevés, qualité visuelle maximale sur les points clés.
; ====================================================================================

[/Script/Engine.GameUserSettings]
; --- Options d'Affichage et de Synchronisation ---
bUseVSync=False
FullscreenMode=1
PreferredFullscreenMode=1
bUseDynamicResolution=False
FrameRateLimit=0.000000

; --- Résolution (Gérée par le script) ---
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080

; --- Options Diverses ---
bUseDesiredScreenHeight=False
bUseHDRDisplayOutput=False
AudioQualityLevel=1

[ScalabilityGroups]
; Qualité des textures au maximum ("Ultra").
sg.ResolutionQuality=100.000000
sg.ViewDistanceQuality=2              ; QUALITÉ DISTANCE POUR PROFIL D. 2 = Haute.
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=3                   ; QUALITÉ DES TEXTURES POUR PROFIL D. 3 = Ultra.
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.AnimationQuality=0
