; ====================================================================================
; Dead by Daylight - Profil Compétitif (par Jules)
; PROFIL B : Moyenne Config
; OBJECTIF : Stabilité, FPS élevés, options graphiques de base.
; ====================================================================================

[/Script/Engine.GameUserSettings]
; --- Options d'Affichage et de Synchronisation ---
bUseVSync=False
FullscreenMode=1
PreferredFullscreenMode=1
bUseDynamicResolution=False
FrameRateLimit=0.000000

; --- Résolution (Gérée par le script) ---
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080

; --- Options Diverses ---
bUseDesiredScreenHeight=False
bUseHDRDisplayOutput=False
AudioQualityLevel=1

[ScalabilityGroups]
; Pour ce profil, la qualité des textures est augmentée à "Moyen".
sg.ResolutionQuality=100.000000
sg.ViewDistanceQuality=1
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=1                   ; QUALITÉ DES TEXTURES POUR PROFIL B. 1 = Moyen.
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.AnimationQuality=0
