; ====================================================================================
; GameUserSettings.ini — Profil C (Haute Config)
; Synchronisé avec Engine.ini pour une haute qualité de textures et une performance stable.
; ====================================================================================

[/Script/Engine.GameUserSettings]
; --- Paramètres d'affichage principaux ---
bUseVSync=False
FullscreenMode=1
PreferredFullscreenMode=1
FrameRateLimit=0.000000
bUseDynamicResolution=False

; --- Résolution (Placeholder) ---
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080

[ScalabilityGroups]
; --- Groupes de qualité graphique (Scalability) ---
sg.ResolutionQuality=100.000000
sg.ViewDistanceQuality=2
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=2                   ; PROFIL C: Qualité des textures (2 = Haute).
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.AnimationQuality=1

[/Script/DeadByDaylight.DBDGameUserSettings]
Crossplay=True
MuteOnFocusLoss=True
TerrorRadiusVisualFeedback=True
